#!/usr/bin/env node

import { Command } from "commander"
import configuration from "./controllers/configuration";
import init from "./controllers/init";
import parser from "./controllers/parser";

init();

const program = new Command();
program.version('2.0.0', '-v, --version', 'Show current verion');

program.description('PONOS is the PRESIB log parser. This version process teh logs generated by PRESIB\'s model version 2.x.x');
program.name('ponos');

program
.command('config')
.option('-o, --output <out_folder_path>', 'set destination forder of the parser', '~/ponosResults')
.action(configuration)

program
.command('parse')
.option('-f, --file <file_path>', 'path for file to parse')
.option('-d, --directory <in_folder_path>', 'path to the folder with logs to parse')
.action(parser);


program.parse(process.argv);